var termdict = {
lusuka:'the Sun, day, daylight',
sani:'to shine, gleam, glitter, beam',
lami:'the Moon, creascent, month',
vuzi:'now (in the moment)',
pana:'now (nowadays)',
runati:'already, yet',
zui:'go, gonna (optional future tense auxiliary)',
kulinia:'again, once more',
nubata:'to rise',
mulubia : 'people~persons (not folk~ethnos)',
gigi : 'many~much',
mukadi : '(a) time (not time the clocks can show)',
tuma : 'to shout~yell~scream',
bari : 'same',
bani : 'other~another',
tisiki : 'different~unlike',
nama : 'happy~content',
kumasi : 'frequent',

rupa : 'I~me (pronoun)',
du : 'you~thou (pronoun sg.)',
ka : 'he~she~it (pronoun)',
raia : 'we (pronoun pl.)',
tura : 'you (pronoun pl.)',
rura : 'they (pronoun pl.)',

riki : 'house',
tiui : 'bee',
pipi : 'man',
lukama : 'hill',
tasi : 'to walk',
harata : 'to hop~jump',
uranisia : 'to sleep~slumber',
banuri : 'to drop',
bulini : 'green',
uasi : 'big',
ridisi : 'small',
ulapia : 'well',
du : 'good',
busa : 'alike',

muli : 'who',
ati : 'what',
ani : 'this',
duki : 'that (rel. pronoun)',
rama : 'all',
tisi : 'each',
runa : 'every',
kuga : 'some',
rubi : 'any',
pazi : 'no~none',

ma : 'at~in~on',
sa : 'to~onto~into',
ki : 'out from',
bu : 'off from',
fibi : 'about',
kuli : 'to~for',
ku : 'by / adverb marker',
la : 'not',
buru : 'one 1',
buna : 'two 2',
fupu : 'three 3',
mimili : 'four 4',
suia : 'five 5',
rumani : 'six 6',
mi : 'seven 7',
hata : 'eight 8',
hulazi : 'nin 9',
parala : 'ten 10',
lasi : 'eleven 11',
suturi : 'twelve 12',
sifi : 'zero 0',
uburi : 'hundred 100',
uluda : 'thousand 1 000',
davani : 'ten thousands 10 000',

dulari : 'long',
numadi : 'woman',

kurali : 'person',
supuli : 'fish',
mumana : 'bird',
mutiri : 'dog',
furiti : 'louse',
analisi : 'tree',
dia : 'seed',
samati : 'leaf',
};